//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::customers::Entity as Customers;
pub use super::invoices::Entity as Invoices;
pub use super::meters::Entity as Meters;
pub use super::payments::Entity as Payments;
pub use super::post::Entity as Post;
pub use super::readings::Entity as Readings;
