//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize,Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq,Deserialize,Serialize)]
#[sea_orm(table_name = "readings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub meter_id: String,
    pub units: i32,
    pub timestamp: DateTime,
    pub period: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::meters::Entity",
        from = "Column::MeterId",
        to = "super::meters::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Meters,
}

impl Related<super::meters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meters.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
